### ISSUE TITLE
Service user stories

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#3]
Hey @mandytaylorlwc, 
Can you please provide us with some service user stories/quotes that you would like included in the app? These could be real or fictional 👍 
Thanks!

**Comment by mandytaylorlwc** [comment]
hi please see below a few examples as an idea (it will take a little longer to get a few more) :-1: 
M. I. had got into debt problems with an energy supplier. He saw his advisor over 4 sessions to tackle the issue. As a result  over £3,500 of debt was written off and he was successful in his application for a £140 Warm Home Discount also. The financial pressure he was feeling has now gone and he feels much happier"

"E.F . did not know which way to turn after a recent seperation . After just 2 adviser appointments , benefits worth £4882.80 have been confirmed as being in payment and an application for further benefits has been put in with the advisor's help. E.F. now feels much more supported and knows that help is always on hand for form filling , advice and money matters"

 "C has previously worked in the same job for a number of years, unfortunately she was subject to some bullying in the workplace which impacted on C's Mental Health specifically her confidence, self esteem and anxiety levels and for the first time she was unemployed.  C accessed employment support and completed Mindfit courses to help improve confidence, self worth and she also completed the Why Worry course, from this she completed volunteering applied for a course on mental health , updated her CV, practised interview techniques and eventually found part time work."

"DK has Fibromyalgia and arthritis in her neck, she has been suffering low moods and anxiety in social settings and becoming more isolated as she was avoiding social situations through panic.   DK attended living well therapy sessions and accessed Behavioural Activation to address negative thinking and emotions.  With support we saw DK increase pleasurable activities and socialise more with improved her anxiety levels and feel better in herself.    DK also felt able after engaging with this therapy to discuss some childhood trauma which has seen her engage in 1 to 1 counselling."

"R.D- female, 66 years of age of Indian background, attended the Living Well sessions held at a community venue.   R.D attended the first session extremely nervous, teary and worried. R.D suffers from sciatica pain and a rotator cuff injury, which has resulted in her feeling miserable, trouble relaxing and difficulty in sleeping. In addition, R.D had lost her daughter to cancer, which resulted in R.D’s condition to heighten due to stress. Each week, R.D attended the session with enthusiasm and a thirst to learn more. Each week, she attended the session acknowledging her strengths and weaknesses. R.D would practice the therapy techniques learnt during the sessions once she returned home- her husband would also participate alongside her; she would return the next week elated announcing the sessions are helping with her mood i.e. she said ‘’ feels less grumpy with children and grandchildren, more motivated, wants to learn more and volunteer’’. 

"CJ is a 22 year old who came into contact with LWC following release from Prison, CJ was referred for support in the community, at assessment CJ was focused on getting back into work or education and wanted to make some positive changes.   CJ had some basic needs to address as she had no income, no GP and her accommodation was not suitable which could lead to recall to prison which was causing her anxiety.    LWC caseworker helped the client find alternative suitable accommodation, made contact with the local alcohol support team and she met with LWC Money Advisors to claim any benefits she was entitled too.  Once accommodation was in place CH engaged well and worked with the employment support team to update CV, disclosure work on interview skills.   CJ has maintained the new tenancy is abstinent from alcohol and is currently volunteering and hoping to secure paid employment in the future"

**Comment by Jen-Harris** [comment]
This is amazing thank you @mandytaylorlwc! Don't worry too much about doing any more - this is plenty!

**Comment by maxgerber** [comment]
Hi @mandytaylorlwc - we're just looking through the user stories now and wondering whether or not they'd be more relatable as first person quotes - e.g. "I started came into contact with LWC about four years ago following my release from prison". What do you reckon?
