### ISSUE TITLE
Basic user details wanted in form 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#4]
Hey @mandytaylorlwc, 
What are the details you wanted to collect from the user at the end of the app? would it just be name, number, email? 
Thanks!

**Comment by mandytaylorlwc** [comment]
Name:
DOB:
Address:
Contact Number:
Email Address:

**Comment by mandytaylorlwc** [comment]
Hi

I have answered everything now and attached our logo.

thanks

Mandy Taylor BA hons, PGCE, MCIH, MIMA (Cert)
Project Manager (Employment, Advice and Guidance)
Lancashire Women’s Centres

Secure email: Mandy.taylor@womenscentre.cjsm.net<mailto:Mandy.taylor@womenscentre.cjsm.net>
#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  or on Facebook at Lancashire Women’s Centres

   [cid:image001.png@01D2F4D2.88F43160]

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                         Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF      Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                    Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                      Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                       Tel. 01772 259211

Freephone 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed. If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women’s Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed
