### ISSUE TITLE
Build Sprint Schedule 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#49]
Hey @mandytaylorlwc / Amber, 
Below is a schedule for the build sprint, including immediate actions needed from you: 

__Monday 15th__:
* LWC to review contract & Deliverables and return amendments/signed copy 
* F&C to send updated designs 

__Tuesday 16th__:
* LWC to feedback on design updates 

__Wednesday 17th Jan - Thursday 25th Jan__
* F&C to build 
* We will keep you updated with progress and changes 
* LWC to be available for questions via Github at least once per day

__Friday 26th Jan__
* F&C to present product to LWC - please let us know when would suit you?
* F&C to make any _*small*_ amends to product following presentation 
* LWC to take away and do 2nd round of user testing 

Please let me know if you have any questions and when would be good for you both on Friday 26th to present. 
Jen & Matt

**Comment by mandytaylorlwc** [comment]
Hi

Sorry for the delay manic week and job interviews etc , we are testing a few more people on the pictures you sent but all the other changes look positive, we need to work on the contact form (GDPR)  and the process and maybe the wording.   I have blocked some time on Friday to give this the attention it needs, I hope this is ok.

Amber is working alongside and doing a lot of the testing so it may be good if she could have her own login on here.

Thanks

**Comment by Jen-Harris** [comment]
Hey @mandytaylorlwc,
Thanks for getting back to us. 

Absolutely let's get Amber a login, if she signs up on Github and then let us know her handle so we can add her to this project. 

If you do have time today it would be great to hear back on the contract/deliverables. 

We think it would be a good idea to have a call tomorrow as we want to update you on a few ideas and questions we have. When would be best? 

Jen & Matt

**Comment by mandytaylorlwc** [comment]
We have time tomorrow as we have booked the morning out to spend some quality time on it.

Thanks

Mandy Taylor BA hons, PGCE, MCIH, MIMA (Cert)
Project Manager (Employment, Advice and Guidance)
Lancashire Women’s Centres

Secure email: Mandy.taylor@womenscentre.cjsm.net<mailto:Mandy.taylor@womenscentre.cjsm.net>
#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  or on Facebook at Lancashire Women’s Centres

   [Lancs Women's Centres logos min size signature]

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                         Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF      Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                    Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                      Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                       Tel. 01772 259211

Freephone 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed. If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women’s Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed

**Comment by Jen-Harris** [comment]
Sounds good, would you be free for a call at 10:30am tomorrow? 
We would like to discuss:
* Contract & Deliverables
* Workflow
* GDPR 
* Form process
* Next steps

**Comment by mandytaylorlwc** [comment]
Yes - that would be great and Amber is currently getting a GIT hub sign in.

thanks

Mandy Taylor BA hons, PGCE, MCIH, MIMA (Cert)
Project Manager (Employment, Advice and Guidance)
Lancashire Women’s Centres

Secure email: Mandy.taylor@womenscentre.cjsm.net<mailto:Mandy.taylor@womenscentre.cjsm.net>
#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  or on Facebook at Lancashire Women’s Centres

   [Lancs Women's Centres logos min size signature]

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                         Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF      Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                    Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                      Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                       Tel. 01772 259211

Freephone 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed. If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women’s Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed

**Comment by mandytaylorlwc** [comment]
We need a consent on the contact form  we were thinking something like this (although could change slightly)
Lancashire Women's Centres (LWC)  want you to understand how our service works and how we store your data.  Please state that you have read and agree to these terms before you continue.   (http://womenscentre.org/terms-conditions) 

! (in bold or highlighted)  ( BOX)  I agree to LWC data storage terms.
LWC will never sell your data and promise to keep any personal details safe and secure, you can change your mind at any time by emailing enquires@womenscentres.org

LWC like to keep in touch with people to tell you about the vital work we do, our fundraising events and opportunities to support or work for us.   Please indicate below if you would like to go on our mailing list and agree to our data storage policy.  (http://womenscentre.org/terms-conditions)

(box) Yes please, I would like to be on Lancashire Women's Centres mailing list for events, support and services.
(box) No Thanks I do not want to be on Lancashire Women's Centres mailing list for events, support and services.

hope that makes sense - we need to create the link on website for the policy to be uploaded when its finished.

thanks

I think we have covered most aspects now

**Comment by Jen-Harris** [comment]
Hey @mandytaylorlwc,
With the above copy it will look something like the screen shot below. 
I'm worried that it's a lot of text. If it's needed for GDPR then let's of course include it all. Let me know what you think?
![image](https://user-images.githubusercontent.com/26116988/35159746-210fbe92-fd33-11e7-9ddb-1dee338bba88.png)

**Comment by mandytaylorlwc** [comment]
I am going to send to our Policy person but to be honest I don’t think we have a choice.   Not good but once we have more than 2 pieces of identifiable data we need authorisation.

I will come back once she has a look.

thanks

Mandy Taylor BA hons, PGCE, MCIH, MIMA (Cert)
Project Manager (Employment, Advice and Guidance)
Lancashire Women’s Centres

Secure email: Mandy.taylor@womenscentre.cjsm.net<mailto:Mandy.taylor@womenscentre.cjsm.net>
#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  or on Facebook at Lancashire Women’s Centres

   [Lancs Women's Centres logos min size signature]

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                         Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF      Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                    Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                      Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                       Tel. 01772 259211

Freephone 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed. If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women’s Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed

**Comment by Jen-Harris** [comment]
Ok great, let us know what they say
