### ISSUE TITLE
New iPad designs for feedback

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#51]
Hey @mandytaylorlwc, 
We've adapted the designs to how we imagine it working on iPad (and therefore hopefully desktop as well!)
It's all the same flow and all can be seen in the [same file as the mobile designs](https://www.figma.com/file/UkADRtfuYVzlYDOaPcPehzhb/Lancashire-Women's-Centre). The only difference is we've taken out some of the additional buttons because that are in the mobile designs because the users should be able to more easily move around because of the visible nav bar. Please let us know your thoughts!

![image](https://user-images.githubusercontent.com/26116988/34951786-48ad83d4-fa0f-11e7-87d5-f60048f01ea7.png)

![image](https://user-images.githubusercontent.com/26116988/34951830-7385ac44-fa0f-11e7-8637-f1032deeb5bd.png)

![image](https://user-images.githubusercontent.com/26116988/34951839-7b9bbe3c-fa0f-11e7-8650-3406139f3a4a.png)

![image](https://user-images.githubusercontent.com/26116988/34951843-8134a4bc-fa0f-11e7-8659-145d6951e6b6.png)

![image](https://user-images.githubusercontent.com/26116988/34951852-883f4b5e-fa0f-11e7-86a0-832567df9b31.png)

![image](https://user-images.githubusercontent.com/26116988/34951857-8de97fc0-fa0f-11e7-98fb-dfcf53cefd65.png)

**Comment by mandytaylorlwc** [comment]
we like this and actually like the picture but again are doing some in house testing

**Comment by mandytaylorlwc** [comment]
Hi

A few word changes at the minute:-

Landing Page - change See real stories to READ real stories
                      - remove the see on Our Services and just leave as Our Services

Contact page - remove Emotional Wellbeing - and say Therapy e.g. Counselling
                        remove Personal Development - and say Courses & Training
                        remove 72 hrs and put shortly

**Comment by Jen-Harris** [comment]
Thank you @mandytaylorlwc,
we'll update the copy to reflect these changes. 
Were there any other additions/amendments to the copy you would like?

**Comment by mandytaylorlwc** [comment]
I have sent some emails with some other bits but I think that seems to be most of the changes for now.

thanks

Mandy Taylor BA hons, PGCE, MCIH, MIMA (Cert)
Project Manager (Employment, Advice and Guidance)
Lancashire Women’s Centres

Secure email: Mandy.taylor@womenscentre.cjsm.net<mailto:Mandy.taylor@womenscentre.cjsm.net>
#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  or on Facebook at Lancashire Women’s Centres

   [Lancs Women's Centres logos min size signature]

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                         Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF      Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                    Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                      Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                       Tel. 01772 259211

Freephone 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed. If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women’s Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed
