### ISSUE TITLE
Mobile vs Desktop vs iPad

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#6]
hey @mandytaylorlwc,
I don't think we confirmed on Monday what device we should design for. 
We're leaning towards mobile - what do you think?
Jen

**Comment by mandytaylorlwc** [comment]
this is where I come unstuck would an app for mobile be android and iphone/ipad friendly or would we have to have one or the other?  

thanks

**Comment by maxgerber** [comment]
Hi @mandytaylorlwc,
So the app will work on all those devices, but for designing we tend to focus on making it look right on one type of screen (mobile, tablet, or desktop). If you're unsure, I know AVA decided to go with a mobile-first design because the women using their service might be in precarious living situations, and their phone would be the easiest way for them to access the internet.

What do you think?
